library(dplyr)
library(ggplot2)
data<-read.table("household_power_consumption.txt",sep=";",skip=1)
data<-tbl_df(data)
names(data) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
subdata<-filter(data,Date=="1/2/2007" | Date=="2/2/2007")
png("plot1.png",width = 480, height = 480, units = "px")
hist(as.numeric(as.character(subdata$Global_active_power)),col="red",xlab="Global Active Power (kilowatts)",main="Global Active Power")
dev.off()
